config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get '/home', to: 'pages#home',as: 'home'
  get '/about', to: 'pages#about', as: 'about'
  get '/contact', to: 'pages#contact', as: 'contact'

  devise_for :users

resources :posts

end

app/models/category.rb
class Category < ActiveRecord::Base

    has_many :postspos

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :categories, :dependent => :destroy
  has_and_belongs_to_many :tags, :dependent => :destroy
  has_and_belongs_to_many :comments, :dependent => :destroy
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts  = Post.all
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def index
  @posts = Post.all

end

def show
  @post = Post.find(params[:id])
end

def new
end

end

app/controllers/user_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BLOG", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-links">
          <%= link_to "Inicio", home_path %>
          <%= link_to "Nosotros", about_path %>
          <%= link_to "Contacto", contact_path %>
        </li>
        <!--<li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>-->
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Register", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_notifications.html.erb
<%# Required by devise and used by the entire app %>
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% elsif alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <% if content_for?(:head) %>
    <%= yield(:head) %>
  <% end %>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <%= render "layouts/navbar" %>
  <%= render "layouts/notifications" %>

  <div class="container">
  <%= yield %>
  </div>

    <footer class="blog-footer">
      <p>Blog creado por la comunidad de <a href="https://www.facebook.com/groups/rubyonrailsespa/">Ruby On Rails en Facebook</a></p>
      <p>
        <a href="#">Ir hacia arriba</a>
      </p>
    </footer>
</body>
</html>

app/views/pages/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/pages/contact.html.erb
<div id="wrapper-contact">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h1>Contáctanos</h1>
      </div>
      <%= simple_form_for :contact do |f| %>
      <div class="panel-body">
        <p><%= f.text_field :name, class: "form-control", placeholder: "Tu nombre" %></p>
        <p><%= f.text_field :email, class: "form-control", placeholder: "Tu e-mail" %></p>
        <p><%= f.text_area :message, class: "form-control", placeholder: "Mensaje para los desarrolladores de este sitio" %></p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-4 col-md-offset-8 col-lg-3 col-lg-offset-9">
            <p>
              <%= f.submit "Enviar", class: "btn btn-success btn-lg btn-block" %>
            </p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">The Bootstrap Blog</h1>
        <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">
<%- if @posts %>
<% else %>

          <div class="blog-post">
            <h2 class="blog-post-title">No hay posts. Esto es de relleno!. Publica un post.</h2>
            <p class="blog-post-meta">December 23, 2013 by <a href="#">Jacob</a></p>

            <p>Publica un post <%= link_to "Nuevo post", new_post_path, class: "btn btn-lg btn-primary" %>

, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
            <blockquote>
              <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </blockquote>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
            <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
          </div><!-- /.blog-post -->
<% end -%>

          <nav>
            <ul class="pager">
              <li><a href="#">Previous</a></li>
              <li><a href="#">Next</a></li>
            </ul>
          </nav>

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

app/views/posts/index.html.erb
<%- @posts.each do |articulo| %>
<div class="panel">
<%= link_to articulo do %>
<img src="http://placehold.it/500x200">
<%= articulo.title %> 
<% end %>
</div>
<% end %>

app/views/posts/show.html.erb
<% content_for :head do %>
<meta name="title" content="<%= @post.metatitulo %>">
<meta name="description" content="<%= @post.metadescricion %>">
<meta name="keywords" content="<%= @post.metapalabrasclave %>">
<% end %>
<div class="panel">
  <div class="panel-heading panel-primary">
    <small><%= l @post.created_at %>
    <h1><%= @post.title %></h1>
  </div>
  <div class="panel-body">
    <%= @post.description %>
  </div>
  <div class="panel-footer">
    <% #fix categories %>
  </div>
</div>